### PR TITLE
Add Intel VAAPI H.264 codec, implement CQP, resize & framerate Intel H.264

### PR DESCRIPTION
**Pull request by marek-g**
This PR:
- adds new Intel VAAPI H.264 codec (to be used on Linux Intel HD systems as an alternative for Intel QSV codec)
- implements CQP setting for Intel VAAPI H.264 & Intel QSV H.264
- implements resize setting for Intel VAAPI H.264 & Intel QSV H.264
- implements framerate setting for Intel VAAPI H.264 & Intel QSV H.264

### CODE REVIEW

**Comment by CineEncoder** [comment]
I have posted this commit on the new branch: prototype/intel_vaapi, I will need to check it out and add translations to other languages. Please tell me what dependencies will need to be installed? Thanks!

**Comment by marek-g** [comment]
Of course! Thank you very much!

The required hardware is Intel HD graphics. The docs says that GMA 4500 or newer should also work with a different driver. If you have secondary graphics card, the Intel needs to be initialized (the best way to ensure it is to have a monitor connected to it and having it showing a screen).
The required software except ffmpeg and QT is (for Arch Linux or Manjaro):

- if it's IntelHD - [intel-media-driver package](https://archlinux.org/packages/?name=intel-media-driver)
- if it's GMA 4500 or newer [libva-intel-driver](https://archlinux.org/packages/?name=libva-intel-driver) and [libva-intel-driver](https://archlinux.org/packages/?name=libva-intel-driver)

For Ubuntu you may need something like [libva-intel-vaapi-driver](https://www.ubuntuupdates.org/package/intel_linux_graphics/Ubuntu/12.10/base/libva-intel-vaapi-driver) and/or [libva-intel-vaapi-driver](https://www.ubuntuupdates.org/package/intel_linux_graphics/Ubuntu/12.10/base/libva-intel-vaapi-driver) and/or https://github.com/intel/media-driver - probably depending on the hardware you have.

I was testing it on latest Linux Manjaro with IntelHD 630 and intel-media-driver package under X11 and Wayland.

**Comment by CineEncoder** [comment]
Hello! Added to the branch 'master'. The only thing I could not test how it would work because my processor does not support this mode.

**Comment by marek-g** [comment]
Great! Thank you very much. I have tested it on two machines - one is i7 8700K, the other is i5 10400 (both with Intel UHD 630) and it works fine on both, so don't worry. Thx!

**Pull request closed without merging**
